---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create user group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp
        state: directory
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: /tmp
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
    - name: download tomcat 10.1.4
      ansible.builtin.get_url:
        url: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.4/bin/apache-tomcat-10.1.4.tar.gz
        dest: /tmp/apache-tomcat-10.1.4